name: test

on:
  pull_request:
    branches: [master]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]
    types: [opened, edited, reopened, synchronize, unlocked]
  push:
    branches: [master]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]

jobs:
  go-test:
    uses: lrstanley/.github/.github/workflows/lang-go-test-matrix.yml@master
    permissions:
      contents: read
    with: { num-minor: 1, num-patch: 2 }
  go-lint:
    uses: lrstanley/.github/.github/workflows/lang-go-lint.yml@master
    permissions:
      checks: write
      contents: read
      pull-requests: read
      security-events: write
      statuses: write
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
          cache-dependency-path: docs/pnpm-lock.yaml
      - run: make docs-build
      - if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist/
      - if: ${{ github.event_name != 'pull_request' }}
        id: deployment
        uses: actions/deploy-pages@v4
